version: '2'
services:
  mdbook:
    image: crimsoncorelabs/mdbook
    container_name: mdbook
    restart: unless-stopped
    volumes:
    - $PWD:/opt/wiki
    ports:
      - 3000:3000
      - 3001:3001
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
